#--------------------公共配置区-------------------
#redis服务器配置
spring:
  redis:
    host: 172.19.7.140
    password:
    port: 6379
    timeout: 180s
    jedis:
      pool:
        max-active: 500
        min-idle: 0
        max-idle: 8
        max-wait: 120s

#--------------------系统配置区-------------------
#数据源配置
hikari:
  master:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://172.19.6.127:3306/wnoa_dev?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false
    username: root
    password: suneee
    maximum-pool-size: 20
    pool-name: master
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
  slave:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://172.19.6.127:3306/wnoa_dev?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false
    username: root
    password: suneee
    maximum-pool-size: 80
    pool-name: slave
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
    read-only: true

#mybatis配置
mybatis:
  mapper-locations: classpath:com/suneee/**/mapper/**/*.xml
  type-aliases-package: com.suneee.**.model
  config-location: classpath:conf/configuration.xml


